# Generated by Django 4.1.7 on 2023-03-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('RED', 'Red'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('WHITE', 'White')], default='WHITE', max_length=32),
        ),
    ]
